
trigger:
- master  # ou a branch que você deseja monitorar

pool:
  vmImage: 'ubuntu-latest'  # Escolha a imagem de máquina virtual desejada

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Versão do Node.js a ser usada
  displayName: 'Instalar o Node.js'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)/front-end'
    customCommand: 'run test'
  continueOnError: true

- script: |
    npm install
    npm start
    npm run build
  displayName: 'Construir o projeto NPM'
  
