
trigger:
- master  # ou a branch que você deseja monitorar

pool:
  vmImage: 'ubuntu-latest'  # Escolha a imagem de máquina virtual desejada

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Versão do Node.js a ser usada
  displayName: 'Instalar o Node.js'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '/customer-app'  # Caminho para o diretório de build
    artifactName: 'npm-artifact'  # Nome do artefato a ser publicado
  displayName: 'Publicar artefatos de build'

- script: |
    npm install
    npm run build
  displayName: 'Construir o projeto NPM'
  
