
trigger:
- master  # ou a branch que você deseja monitorar

pool:
  vmImage: 'ubuntu-latest'  # Escolha a imagem de máquina virtual desejada

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Versão do Node.js a ser usada
  displayName: 'Instalar o Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run test'
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/front-end/customer-app'
    mergeTestResults: true
    testRunTitle: 'Publish Test Results'