trigger:
- main
 
pool:
  vmImage: 'ubuntu-latest'
 
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Versão do Node.js a ser usada
  displayName: 'Instalar o Node.js'


- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)/front-end/customer-app'
    verbose:  true
  displayName: 'npm install'
  
- task: Npm@1
  inputs:
    command: custom
    workingDir: '$(Build.SourcesDirectory)/front-end/customer-app'
    customCommand: 'run-script build --prod'
  displayName: 'npm build'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'labservicescdn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account show
      az storage blob upload-batch --account-name storagefate -s "/front-end/customer-app/build/*" -d '$web'